# -*- coding: utf-8 -*-
"""Template Eksperimen MSML_robertus_p

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XROUfYla_F4_q62l8htAd6LrNIRai9wq

# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
import os

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams['figure.figsize'] = (10, 6)

print('Semua library berhasil diimport!')
print(f'Pandas version : {pd.__version__}')
print(f'NumPy version  : {np.__version__}')

"""# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan
"""

RAW_PATH = 'C:/Users/Panda/Downloads/Eksperimen_SML_robertus_p/preprocessing/heart_raw.csv'

df = pd.read_csv(RAW_PATH)
print(f'Dataset berhasil dimuat!')
print(f'Jumlah baris  : {df.shape[0]}')
print(f'Jumlah kolom  : {df.shape[1]}')
print(f'Nama kolom    : {df.columns.tolist()}')

df.head()

df.tail()

df.sample(5, random_state=42)

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

df.info()

df.describe()

df.describe(include='all').T

missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing (%)': missing_pct
})
missing_df = missing_df[missing_df['Missing Count'] > 0]

if missing_df.empty:
    print('Tidak ada missing values pada dataset ini.')
else:
    print('Kolom dengan missing values:')
    display(missing_df)

fig, ax = plt.subplots(figsize=(10, 4))
missing_counts = df.isnull().sum()
colors = ['#E24B4A' if v > 0 else '#1D9E75' for v in missing_counts]
bars = ax.bar(missing_counts.index, missing_counts.values, color=colors, edgecolor='white')
ax.set_title('Missing Values per Kolom', fontsize=14, fontweight='bold')
ax.set_xlabel('Kolom')
ax.set_ylabel('Jumlah Missing')
ax.tick_params(axis='x', rotation=45)
for bar, val in zip(bars, missing_counts.values):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1,
            str(val), ha='center', va='bottom', fontsize=9)
plt.tight_layout()
plt.show()
print(f'Total missing values: {df.isnull().sum().sum()}')

dup_count = df.duplicated().sum()
print(f'Jumlah baris duplikat: {dup_count}')

if dup_count > 0:
    print('Contoh baris duplikat:')
    print(df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist()).head(10))

target_counts = df['target'].value_counts()
target_pct = df['target'].value_counts(normalize=True) * 100

print('Distribusi Target Variable:')
print(f'  0 (No Disease): {target_counts[0]} ({target_pct[0]:.1f}%)')
print(f'  1 (Disease)   : {target_counts[1]} ({target_pct[1]:.1f}%)')

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

colors_target = ['#3B8BD4', '#E24B4A']
bars = axes[0].bar(['No Disease (0)', 'Disease (1)'], target_counts.values,
                    color=colors_target, edgecolor='white', linewidth=1.5)
axes[0].set_title('Distribusi Target (Bar)', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Jumlah')
for bar, val in zip(bars, target_counts.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 3,
                 str(val), ha='center', va='bottom', fontsize=11, fontweight='bold')

axes[1].pie(target_counts.values, labels=['No Disease (0)', 'Disease (1)'],
            colors=colors_target, autopct='%1.1f%%', startangle=90,
            textprops={'fontsize': 11})
axes[1].set_title('Distribusi Target (Pie)', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
print(f'Kolom numerik: {numeric_cols}')

fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col], bins=30, color='#3B8BD4', edgecolor='white', alpha=0.8)
    axes[i].axvline(df[col].mean(), color='#E24B4A', linestyle='--', linewidth=2, label=f'Mean: {df[col].mean():.1f}')
    axes[i].axvline(df[col].median(), color='#EF9F27', linestyle='--', linewidth=2, label=f'Median: {df[col].median():.1f}')
    axes[i].set_title(f'Distribusi {col}', fontsize=12, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frekuensi')
    axes[i].legend(fontsize=9)

axes[-1].set_visible(False)
plt.suptitle('Distribusi Fitur Numerik', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 5, figsize=(18, 5))

for i, col in enumerate(numeric_cols):
    axes[i].boxplot(df[col], patch_artist=True,
                    boxprops=dict(facecolor='#E6F1FB', color='#185FA5'),
                    medianprops=dict(color='#E24B4A', linewidth=2),
                    whiskerprops=dict(color='#185FA5'),
                    flierprops=dict(marker='o', color='#E24B4A', alpha=0.5))
    axes[i].set_title(col, fontsize=11, fontweight='bold')
    axes[i].set_xlabel('')

plt.suptitle('Boxplot Fitur Numerik (Deteksi Outlier)', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

cat_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

fig, axes = plt.subplots(2, 4, figsize=(18, 10))
axes = axes.flatten()
palette = ['#3B8BD4', '#E24B4A', '#1D9E75', '#EF9F27']

for i, col in enumerate(cat_cols):
    counts = df[col].value_counts().sort_index()
    bars = axes[i].bar(counts.index.astype(str), counts.values,
                        color=palette[:len(counts)], edgecolor='white')
    axes[i].set_title(f'Distribusi {col}', fontsize=11, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Jumlah')
    for bar, val in zip(bars, counts.values):
        axes[i].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                     str(val), ha='center', va='bottom', fontsize=9)

plt.suptitle('Distribusi Fitur Kategorikal', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 5, figsize=(20, 5))

for i, col in enumerate(numeric_cols):
    for target_val, color, label in zip([0, 1], ['#3B8BD4', '#E24B4A'], ['No Disease', 'Disease']):
        data = df[df['target'] == target_val][col]
        axes[i].hist(data, bins=20, alpha=0.6, color=color, label=label, edgecolor='white')
    axes[i].set_title(f'{col} vs Target', fontsize=11, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].legend(fontsize=8)

plt.suptitle('Distribusi Fitur Numerik berdasarkan Target', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 4, figsize=(20, 10))
axes = axes.flatten()

for i, col in enumerate(cat_cols):
    ct = pd.crosstab(df[col], df['target'])
    ct.plot(kind='bar', ax=axes[i], color=['#3B8BD4', '#E24B4A'],
            edgecolor='white', rot=0, legend=(i == 0))
    axes[i].set_title(f'{col} vs Target', fontsize=11, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Jumlah')
    if i == 0:
        axes[i].legend(['No Disease', 'Disease'], fontsize=9)

plt.suptitle('Fitur Kategorikal vs Target', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(13, 10))

corr = df.corr(numeric_only=True)
mask = np.triu(np.ones_like(corr, dtype=bool))

sns.heatmap(corr, mask=mask, annot=True, fmt='.2f',
            cmap='RdBu_r', center=0, vmin=-1, vmax=1,
            linewidths=0.5, ax=ax, cbar_kws={'shrink': 0.8})

ax.set_title('Correlation Matrix', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

target_corr = df.corr(numeric_only=True)['target'].drop('target').sort_values(key=abs, ascending=False)

fig, ax = plt.subplots(figsize=(10, 6))
colors = ['#E24B4A' if v > 0 else '#3B8BD4' for v in target_corr.values]
bars = ax.barh(target_corr.index, target_corr.values, color=colors, edgecolor='white')
ax.axvline(0, color='black', linewidth=0.8)
ax.set_title('Korelasi Fitur terhadap Target', fontsize=14, fontweight='bold')
ax.set_xlabel('Korelasi')

for bar, val in zip(bars, target_corr.values):
    ax.text(val + (0.01 if val >= 0 else -0.01), bar.get_y() + bar.get_height()/2,
            f'{val:.3f}', va='center', ha='left' if val >= 0 else 'right', fontsize=9)

plt.tight_layout()
plt.show()

print('\nFitur dengan korelasi tertinggi terhadap target:')
print(target_corr.head(5))

print('='*55)
print('         RINGKASAN EDA - HEART DISEASE DATASET')
print('='*55)
print(f'Jumlah sampel          : {df.shape[0]}')
print(f'Jumlah fitur           : {df.shape[1] - 1}')
print(f'Missing values         : {df.isnull().sum().sum()}')
print(f'Duplikat               : {df.duplicated().sum()}')
print(f'Target distribution    : {dict(df["target"].value_counts())}')
print()
print('Outlier per kolom numerik (IQR method):')
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    n_out = ((df[col] < lower) | (df[col] > upper)).sum()
    print(f'  {col:<12}: {n_out} outlier')
print('='*55)

"""# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.
"""

df_clean = df.copy()
print(f'Salinan dataset dibuat. Shape: {df_clean.shape}')

before = len(df_clean)
df_clean = df_clean.drop_duplicates()
after = len(df_clean)

print(f'Sebelum  : {before} baris')
print(f'Sesudah  : {after} baris')
print(f'Dihapus  : {before - after} duplikat')

print('Missing values sebelum handling:')
print(df_clean.isnull().sum())

for col in df_clean.select_dtypes(include=[np.number]).columns:
    if df_clean[col].isnull().any():
        median_val = df_clean[col].median()
        df_clean[col].fillna(median_val, inplace=True)
        print(f'  Kolom "{col}" diisi median: {median_val:.2f}')

print(f'\nTotal missing values sesudah: {df_clean.isnull().sum().sum()}')

numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

print('Penanganan outlier dengan IQR Capping:')
print('-' * 50)

for col in numeric_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    n_outlier = ((df_clean[col] < lower) | (df_clean[col] > upper)).sum()
    df_clean[col] = df_clean[col].clip(lower=lower, upper=upper)
    print(f'{col:<12}: {n_outlier} outlier → di-cap ke [{lower:.2f}, {upper:.2f}]')

print('-' * 50)
print(f'Shape setelah outlier handling: {df_clean.shape}')

fig, axes = plt.subplots(2, 5, figsize=(20, 8))

for i, col in enumerate(numeric_cols):
    axes[0, i].boxplot(df[col], patch_artist=True,
                        boxprops=dict(facecolor='#FAEEDA', color='#BA7517'),
                        medianprops=dict(color='#E24B4A', linewidth=2))
    axes[0, i].set_title(f'{col}\n(Sebelum)', fontsize=10)

    axes[1, i].boxplot(df_clean[col], patch_artist=True,
                        boxprops=dict(facecolor='#E1F5EE', color='#0F6E56'),
                        medianprops=dict(color='#E24B4A', linewidth=2))
    axes[1, i].set_title(f'{col}\n(Sesudah)', fontsize=10)

plt.suptitle('Outlier Handling: Sebelum vs Sesudah', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

df_clean['age_group'] = pd.cut(
    df_clean['age'],
    bins=[0, 40, 55, 70, 100],
    labels=[0, 1, 2, 3]
).astype(int)

df_clean['chol_age_ratio'] = df_clean['chol'] / (df_clean['age'] + 1)

print('Fitur baru berhasil ditambahkan:')
print(f'  age_group     : {df_clean["age_group"].value_counts().to_dict()}')
print(f'  chol_age_ratio: min={df_clean["chol_age_ratio"].min():.2f}, max={df_clean["chol_age_ratio"].max():.2f}, mean={df_clean["chol_age_ratio"].mean():.2f}')
print(f'\nShape setelah feature engineering: {df_clean.shape}')
df_clean.head(3)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

ct_age = pd.crosstab(df_clean['age_group'], df_clean['target'])
ct_age.plot(kind='bar', ax=axes[0], color=['#3B8BD4', '#E24B4A'],
             edgecolor='white', rot=0)
axes[0].set_title('Age Group vs Target', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Age Group (0=<40, 1=40-55, 2=55-70, 3=>70)')
axes[0].legend(['No Disease', 'Disease'])

for target_val, color, label in zip([0, 1], ['#3B8BD4', '#E24B4A'], ['No Disease', 'Disease']):
    data = df_clean[df_clean['target'] == target_val]['chol_age_ratio']
    axes[1].hist(data, bins=25, alpha=0.6, color=color, label=label, edgecolor='white')
axes[1].set_title('Chol/Age Ratio vs Target', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Chol Age Ratio')
axes[1].set_ylabel('Frekuensi')
axes[1].legend()

plt.tight_layout()
plt.show()

scale_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'chol_age_ratio']

print('Statistik sebelum scaling:')
print(df_clean[scale_cols].describe().loc[['mean', 'std', 'min', 'max']].round(3))

scaler = StandardScaler()
df_clean[scale_cols] = scaler.fit_transform(df_clean[scale_cols])

print('\nStatistik sesudah scaling:')
print(df_clean[scale_cols].describe().loc[['mean', 'std', 'min', 'max']].round(3))

print(f'\nShape setelah scaling: {df_clean.shape}')

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i, col in enumerate(scale_cols):
    axes[i].hist(df_clean[col], bins=30, color='#1D9E75', edgecolor='white', alpha=0.8)
    axes[i].set_title(f'{col} (setelah scaling)', fontsize=10, fontweight='bold')
    axes[i].set_xlabel('Nilai')
    axes[i].set_ylabel('Frekuensi')

plt.suptitle('Distribusi Fitur Setelah StandardScaler', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

TARGET_COL = 'target'

X = df_clean.drop(columns=[TARGET_COL])
y = df_clean[TARGET_COL]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print('Train-Test Split Selesai:')
print(f'  Total sampel  : {len(df_clean)}')
print(f'  X_train shape : {X_train.shape}')
print(f'  X_test shape  : {X_test.shape}')
print(f'  y_train dist  : {dict(y_train.value_counts())}')
print(f'  y_test dist   : {dict(y_test.value_counts())}')

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

for ax, y_data, title in zip(axes, [y_train, y_test], ['Train Set', 'Test Set']):
    counts = y_data.value_counts()
    ax.bar(['No Disease (0)', 'Disease (1)'], counts.values,
           color=['#3B8BD4', '#E24B4A'], edgecolor='white')
    ax.set_title(f'Distribusi Target - {title}', fontweight='bold')
    ax.set_ylabel('Jumlah')
    for j, v in enumerate(counts.values):
        ax.text(j, v + 0.5, str(v), ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

OUTPUT_DIR = 'heart_preprocessing'
os.makedirs(OUTPUT_DIR, exist_ok=True)

df_clean.to_csv(f'{OUTPUT_DIR}/heart_preprocessing.csv', index=False)

train_df = pd.concat([X_train, y_train], axis=1)
test_df  = pd.concat([X_test,  y_test],  axis=1)

train_df.to_csv(f'{OUTPUT_DIR}/heart_train.csv', index=False)
test_df.to_csv(f'{OUTPUT_DIR}/heart_test.csv',   index=False)

print('Dataset berhasil disimpan!')
print(f'  heart_preprocessing.csv : {df_clean.shape}')
print(f'  heart_train.csv         : {train_df.shape}')
print(f'  heart_test.csv          : {test_df.shape}')
print(f'\nSemua file ada di folder: {OUTPUT_DIR}/')

for f in os.listdir(OUTPUT_DIR):
    path = os.path.join(OUTPUT_DIR, f)
    size = os.path.getsize(path)
    print(f'  {f} ({size:,} bytes)')

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print('='*50)
print('   SANITY CHECK - Model Baseline')
print('='*50)
print(f'Algoritma      : Random Forest')
print(f'Test Accuracy  : {acc:.4f} ({acc*100:.2f}%)')
print()
print('Classification Report:')
print(classification_report(y_test, y_pred, target_names=['No Disease', 'Disease']))

importances = model.feature_importances_
feat_names = X_train.columns.tolist()
sorted_idx = np.argsort(importances)[::-1]

fig, ax = plt.subplots(figsize=(12, 5))
bars = ax.bar(range(len(importances)), importances[sorted_idx],
               color='#3B8BD4', edgecolor='white')
ax.set_xticks(range(len(importances)))
ax.set_xticklabels([feat_names[i] for i in sorted_idx], rotation=45, ha='right')
ax.set_title('Feature Importance (Random Forest Baseline)', fontsize=13, fontweight='bold')
ax.set_ylabel('Importance Score')

plt.tight_layout()
plt.show()

print('\nTop 5 fitur terpenting:')
for i in sorted_idx[:5]:
    print(f'  {feat_names[i]:<18}: {importances[i]:.4f}')